// hams-chat/src/lib/ai-chat/components/LeftRail.svelte
<script lang="ts">
  import { 
    SidebarToggleIconA, 
    SidebarToggleIconB, 
    SidebarToggleIconC,
    SidebarToggleIconD,
    GearIcon,
  } from "../icons";
  import { chatUI } from "../stores/chatUI";
  import type { LeftTab } from "../types";

  function clickTab(t: LeftTab) {
    chatUI.setLeftTab(t);
    if ($chatUI.leftCollapsed) chatUI.toggleLeftCollapsed();
  }

  function railClass(active?: boolean) {
    return [
      "relative grid h-11 w-11 place-items-center rounded-2xl transition",
      active ? "bg-black/90 text-white shadow-sm" : "text-black/60 hover:bg-black/5",
    ].join(" ");
  }
</script>

<div class="flex h-full w-[72px] flex-col items-center justify-between bg-black/[0.03] py-3">
  <div class="flex flex-col items-center gap-2">
    <!-- svelte-ignore element_invalid_self_closing_tag -->
    <div class="h-11 w-11 rounded-2xl bg-black/10" >
      <a href="/" aria-label="메인으로" title="메인으로">
        <img src="/logo.svg" alt="HC" class="h-full w-full p-1" />
      </a>
    </div>

    <div class="mt-2 flex flex-col gap-2">
      <button type="button" class={railClass($chatUI.leftTab === "friends")} on:click={() => clickTab("friends")}>
        <span class="text-lg">👤</span>
      </button>

      <button type="button" class={railClass($chatUI.leftTab === "chats")} on:click={() => clickTab("chats")}>
        <span class="text-lg">💬</span>
        <span class="absolute -right-1 -top-1 rounded-full bg-orange-500 px-1.5 py-0.5 text-[11px] font-semibold text-white shadow-sm">1+</span>
      </button>

      <button type="button" class={railClass($chatUI.leftTab === "more")} on:click={() => clickTab("more")}>
        <span class="text-lg">⋯</span>
      </button>
    </div>
  </div>

  <div class="flex flex-col items-center gap-2">
    <button
      type="button"
      on:click={() => chatUI.toggleLeftCollapsed()}
      class="grid h-11 w-11 place-items-center rounded-2xl text-black/60 hover:bg-black/5"
      aria-label="목록 접기/펼치기"
      title="목록 접기/펼치기"
    >
      {@html SidebarToggleIconA({ collapsed: $chatUI.leftCollapsed })}
    </button>

    <button type="button" class="grid h-11 w-11 place-items-center rounded-2xl text-black/60 hover:bg-black/5" aria-label="설정">
      <span class="text-lg">⚙️</span>
    </button>
    <!-- <button
      type="button"
      class="relative grid h-11 w-11 place-items-center rounded-2xl transition
        ring-1 ring-black/5 shadow-sm active:scale-[0.98]
        bg-white/70 text-black/70 hover:bg-white hover:text-black/80"
      aria-label="설정"
    >
      {@html GearIcon({ size: 20 })}
    </button> -->
  </div>
</div>

// portfolio/app/(content-header)/ai-chat/components/LeftRail.tsx
// app/(content-header)/ai-chat/components/LeftRail.tsx
"use client";

import { useChatUIStore, type LeftTab } from "../store";

function RailButton({
  active,
  badge,
  onClick,
  children,
}: {
  active?: boolean;
  badge?: string;
  onClick: () => void;
  children: React.ReactNode;
}) {
  return (
    <button
      type="button"
      onClick={onClick}
      className={[
        "relative grid h-11 w-11 place-items-center rounded-2xl transition",
        active ? "bg-black/90 text-white shadow-sm" : "text-black/60 hover:bg-black/5",
      ].join(" ")}
    >
      {children}
      {badge ? (
        <span className="absolute -right-1 -top-1 rounded-full bg-orange-500 px-1.5 py-0.5 text-[11px] font-semibold text-white shadow-sm">
          {badge}
        </span>
      ) : null}
    </button>
  );
}

export default function LeftRail() {
  const leftTab = useChatUIStore((s) => s.leftTab);
  const leftCollapsed = useChatUIStore((s) => s.leftCollapsed);
  const setLeftTab = useChatUIStore((s) => s.setLeftTab);
  const toggleLeftCollapsed = useChatUIStore((s) => s.toggleLeftCollapsed);

  const clickTab = (t: LeftTab) => {
    setLeftTab(t);
    // 리스트를 접어놓은 상태에서 탭을 누르면 자동 펼치기(카톡 느낌)
    if (leftCollapsed) toggleLeftCollapsed();
  };

  return (
    <div className="flex h-full w-[72px] flex-col items-center justify-between bg-black/[0.03] py-3">
      <div className="flex flex-col items-center gap-2">
        <div className="h-11 w-11 rounded-2xl bg-black/10" />

        <div className="mt-2 flex flex-col gap-2">
          <RailButton active={leftTab === "friends"} onClick={() => clickTab("friends")}>
            <span className="text-lg">👤</span>
          </RailButton>

          <RailButton
            active={leftTab === "chats"}
            badge="1+"
            onClick={() => clickTab("chats")}
          >
            <span className="text-lg">💬</span>
          </RailButton>

          <RailButton active={leftTab === "more"} onClick={() => clickTab("more")}>
            <span className="text-lg">⋯</span>
          </RailButton>
        </div>
      </div>

      <div className="flex flex-col items-center gap-2">
        <button
          type="button"
          onClick={toggleLeftCollapsed}
          className="grid h-11 w-11 place-items-center rounded-2xl text-black/60 hover:bg-black/5"
          aria-label="목록 접기/펼치기"
          title="목록 접기/펼치기"
        >
          <span className="text-lg">{leftCollapsed ? "⫶" : "⫷"}</span>
        </button>

        <button
          type="button"
          className="grid h-11 w-11 place-items-center rounded-2xl text-black/60 hover:bg-black/5"
          aria-label="설정"
        >
          <span className="text-lg">⚙️</span>
        </button>
      </div>
    </div>
  );
}
